// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2421.Vulcan.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2421.Vulcan.Robot;
import org.usfirst.frc2421.Vulcan.subsystems.Drive;
import java.lang.Math;
import java.util.Timer;

/**
 *
 */
public class AutonomousCommand extends Command {
	public boolean noBubbles = false;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutonomousCommand() {
    	

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=R	EQUIRES
    	
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	double speed = .3;
    	try{
    		double[] sizeArray = Robot.vision.getNumberArray("size", Robot.def);
    		double[] xArray = Robot.vision.getNumberArray("x", Robot.def);
    		double angle = 45;
    		if(sizeArray.length > 3){
    			double sum = sizeArray[0] + sizeArray[1] + sizeArray[2];
    			double xCircum = (angle/180)*(241-38.8*Math.log(sum))*(Math.PI);
    			if(xArray[0] < xArray[2]){
    				Drive.setLeft(1);
    				Drive.setRight(1);
    				new java.util.Timer().schedule(
    						new java.util.TimerTask() {
    							@Override
    							public void run() {
    								//Drive.setLeft(0);
    								//Drive.setRight(0);
    							}
    						}, 2000
    				);
    				Drive.setLeft(1);
    				Drive.setRight(-1);
    				new java.util.Timer().schedule(
    						new java.util.TimerTask() {
    							@Override
    							public void run() {
    								Drive.setLeft(0);
    								Drive.setRight(0);
    							}
    						}, 1500
    				);
    			}
    			else if(xArray[0] > xArray[2]){
    				
    				
    			}
    		}
    		double c = 0.005;
    		double d = .0005;
    		double avgSize = (sizeArray[0] + sizeArray[1])/2;
    		double midpoint = (xArray[0] + xArray[1])/2;
    		double ds = (320-midpoint)*c*avgSize*d;

    		System.out.println(ds);
    		Drive.setLeft(speed+ds);
    		Drive.setRight(speed-ds);
    	}
    	catch(Exception ex){
    		noBubbles = true;
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	if(Robot.vision.getNumberArray("size", Robot.def).length>0)
    		return Robot.vision.getNumberArray("size", Robot.def)[0]>100.0;
        else
        	
        	return noBubbles;
    }

    // Called once after isFinished returns true
    protected void end() {
    	
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
