// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2421.Vulcan.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2421.Vulcan.Robot;
import org.usfirst.frc2421.Vulcan.subsystems.Drive;
import java.lang.Math;
import edu.wpi.first.wpilibj.Timer;

/**
 *
 */
public class AutonomousCommand extends Command {
	public static boolean noBubbles = false;
	boolean end = false;
	public Command zach = new ZachCommand();
	public Command josh = new JoshCommand();
	public static Timer time = new Timer();
	private static double currentTime = 0;
	public static double[] sizeArray;
	public static double[] xArray;
	static double avgLength = 0;
	static double angle = 45;
	static int counter = 0;
	static int lengthSum = 0;
	static double c;
	static double d;
	static double avgSize;
	static double midpoint;
	static double ds;
	static double sum;
	static double xCircum;
	static double distConstant = 61;
	static double speed = .3;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutonomousCommand() {
    	

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=R	EQUIRES
    	
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	time.start();
		zach();		
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	try{
    		updateVisionArrays();
			if(sizeArray.length>1 && sizeArray[0]<120.0){
				josh();
			}
			else
			{
				Drive.setLeft(0);
				Drive.setRight(0);
			}
    	}
    	catch(Exception ex){
    		noBubbles = true;
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	System.out.println("FINISHED");
    	if(sizeArray.length>0)
    		return sizeArray[0]>120.0;
        else
        	return noBubbles;
    }

    // Called once after isFinished returns true
    protected void end() {
    	
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	
    }
    public static void updateVisionArrays(){
    	sizeArray = Robot.vision.getNumberArray("size", Robot.def);
		xArray = Robot.vision.getNumberArray("x", Robot.def);
    }
    public static double arrayAvgLength(){
    	currentTime = time.get();
    	while(time.get() < (currentTime + 2)){
    		updateVisionArrays();
    		lengthSum = (lengthSum + sizeArray.length);
    		counter += 1;
    	}
    	return (lengthSum/counter);
    }
    public static void josh(){
		c = 0.0075;
		d = 0.0006;
		System.out.println(ds);
		avgSize = (sizeArray[0] + sizeArray[1])/2;
		midpoint = (xArray[0] + xArray[1])/2;
		ds = (midpoint-320)*c*avgSize*d;
		Drive.setLeft(speed+ds);
		Drive.setRight(speed-ds);
    }
    
    public static void zach(){
    	updateVisionArrays();
    	avgLength = arrayAvgLength();
    	System.out.println(avgLength);
		if(avgLength > 2.5){
			sum = sizeArray[0] + sizeArray[1] + sizeArray[2];
			if(sum < 200){
    			xCircum = (angle/180)*(241-38.8*Math.log(sum))*(Math.PI);
    			if(xArray[0] < xArray[2]){
    				currentTime = time.get();
    				while(time.get() < (currentTime + .25)){
    					Drive.setLeft(-.5);
    					Drive.setRight(.5);    					
    				}
    				Drive.setLeft(0);
    				Drive.setRight(0);
    				currentTime = time.get();
    				while(time.get() < currentTime + (xCircum/distConstant)){
    					Drive.setLeft(.5);
    					Drive.setRight(.5);
    				}
    				Drive.setLeft(0);
    				Drive.setRight(0);
    				currentTime = time.get();
    				while(time.get() < (currentTime + .25)){
    					Drive.setLeft(.5);
    					Drive.setRight(-.5);
    				}
    				Drive.setLeft(0);
    				Drive.setRight(0);
    			}
    			else if(xArray[0] > xArray[2]){
    				currentTime = time.get();
    				while(time.get() < (currentTime + .25)){
    					Drive.setLeft(.5);
    					Drive.setRight(-.5);    					
    				}
    				Drive.setLeft(0);
    				Drive.setRight(0);
    				currentTime = time.get();
    				while(time.get() < currentTime + (xCircum/distConstant)){
    					Drive.setLeft(.5);
    					Drive.setRight(.5);
    				}
    				Drive.setLeft(0);
    				Drive.setRight(0);
    				currentTime = time.get();
    				while(time.get() < (currentTime + .35)){
    					Drive.setLeft(-.5);
    					Drive.setRight(.5);
    				}
    				Drive.setLeft(0);
    				Drive.setRight(0);
    			}
			}
		}
    }
}
